services:
 postgres:
 image: postgis/postgis:16-3.4
 environment
 POSTGRES_DB: evdb
 POSTGRES_USER: postgres
 POSTGRES_PASSWORD; postgres
 ports:
 - '5432:5432'
 redis:
 image:redis:7
 ports:
 -'6379:6379'
